version: '3.9'
services:
  app:
    image: anonymized-image-processor
    build:
      context: .
      dockerfile: Dockerfile
      target: ts-compiler
    volumes:
      - .:/usr/app
    ports:
      - 9229:9229
    depends_on:
      - db
    env_file:
      - .env
    command: ["npm", "run", "build:dev"]
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data